print("Youssef mohamed salah")
print("18 years old")
print("Computer and communications")
print("grad year is 2027")
print("Favorite team is software team")
print("don't know what to write for the last commit")